### ISSUE TITLE
CreateProcessW failed

### ISSUE THREAD

**Issue by rainman74** [M2Team/NanaRun#2]
Doesn't work! MinSudo in a definied %PATH% Folder (e.g. D:\Apps\Commands\bin)

```
MinSudo 1.0 Preview 2 (Build 18)
(c) M2-Team and Contributors. All rights reserved.

[Error] CreateProcessW failed.
```

But:
Works: MinSudo 1.0 Preview 2 (Build 18) **not** in any definied %PATH% Folder (D:\)
Works: MinSudo 1.0 Preview 1 (Build 5) also in a definied %PATH% Folder (D:\Apps\Commands\bin)

**Comment by MouriNaruto** [comment]
Which command line you used in MinSudo?

Kenji Mouri

**Comment by rainman74** [comment]
WORKS (CMD will be elevated):
```
C:\>minsudo
MinSudo 1.0 Preview 1 (Build 5)
(c) M2-Team and Contributors. All rights reserved.

Microsoft Windows [Version 10.0.19044.1739]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\>
```

ERROR:
```
C:\>minsudo
MinSudo 1.0 Preview 2 (Build 18)
(c) M2-Team and Contributors. All rights reserved.

[Error] CreateProcessW failed.

C:\>
```

**Comment by MouriNaruto** [comment]
What the path you put the MinSudo.exe?

Kenji Mouri

**Comment by rainman74** [comment]
WORKS (CMD will be elevated):
```
C:\>minsudo net stop USBDLM
MinSudo 1.0 Preview 1 (Build 5)
(c) M2-Team and Contributors. All rights reserved.

USBDLM wird beendet.
USBDLM wurde erfolgreich beendet.


C:\>
```

ERROR:
```
C:\>minsudo net stop USBDLM
MinSudo 1.0 Preview 2 (Build 18)
(c) M2-Team and Contributors. All rights reserved.

[Error] CreateProcessW failed.

C:\>
```

**Comment by rainman74** [comment]
> What the path you put the MinSudo.exe?
> 
> Kenji Mouri

D:\Apps\Commands\bin\minsudo.exe

**Comment by rainman74** [comment]
WORKS, if not in PATH
```
D:\Downloads\NanaRun_1.0_Preview2_1.0.18.0\x64>MinSudo.exe net stop USBDLM
MinSudo 1.0 Preview 2 (Build 18)
(c) M2-Team and Contributors. All rights reserved.

USBDLM wird beendet.
USBDLM wurde erfolgreich beendet.

D:\Downloads\NanaRun_1.0_Preview2_1.0.18.0\x64>
```

**Comment by MouriNaruto** [comment]
I have reproduced this issue.

I found this issue will be happened when the current directory is not the root of the drive.

![image](https://user-images.githubusercontent.com/10867563/171814716-fc08c0b6-5ee6-417b-9e20-131ca0b0d02a.png)
![image](https://user-images.githubusercontent.com/10867563/171814743-ad3981e3-d035-4d37-8759-ee13618ad42f.png)
![image](https://user-images.githubusercontent.com/10867563/171814810-b078236d-7dac-4114-99cd-8ce0b0301acc.png)

Kenji Mouri

**Comment by MouriNaruto** [comment]
I have fixed this issue.

It was caused by command line parser behavior. (NanaRun's command line parser follows the rule from https://docs.microsoft.com/en-us/cpp/c-language/parsing-c-command-line-arguments?view=msvc-170.)

Kenji Mouri

**Comment by MouriNaruto** [comment]
> If you build a test version, I'll be happy to test it and confirm functionality.

[MinSudo_20220608.zip](https://github.com/M2Team/NanaRun/files/8862146/MinSudo_20220608.zip)

Here is the binary for the test.

Kenji Mouri

**Comment by rainman74** [comment]
> > If you build a test version, I'll be happy to test it and confirm functionality.
> 
> [MinSudo_20220608.zip](https://github.com/M2Team/NanaRun/files/8862146/MinSudo_20220608.zip)
> 
> Here is the binary for the test.
> 
> Kenji Mouri

runs perfectly without errors now!
